#  menu items
#[[main]]
#  name = "Blog"
#  weight = 3
#  url = "blog/"

[[main]]
  name = "Databases"
  weight = 2
  url = "databases/"
  identifier = "db"

#[[main]]
#  name = "Tutorials"
#  weight = 3
#  url = "tutorials/"

#[[main]]
#  name = "Example"
#  weight = 3
#  url = "https://docs.neuralvibes.com"

 [[main]]
   name = "Posts"
   weight = 5
   url = "blog/"
   
 [[main]]
   name = "Contribute"
   weight = 4
   url = "support/"
